# Generated by Django 3.0.5 on 2020-05-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='MODEL NAME METHOD')),
            ],
        ),
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('metamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.MetaModel')),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
            bases=('mainapp.metamodel',),
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('metamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.MetaModel')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
            bases=('mainapp.metamodel',),
        ),
        migrations.CreateModel(
            name='MarkModel',
            fields=[
                ('metamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.MetaModel')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AreaModel')),
            ],
            options={
                'verbose_name_plural': 'Quality marks',
            },
            bases=('mainapp.metamodel',),
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('metamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.MetaModel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.CountryModel')),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
            bases=('mainapp.metamodel',),
        ),
        migrations.CreateModel(
            name='SignModel',
            fields=[
                ('metamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.MetaModel')),
                ('sign', models.CharField(max_length=1, null=True, verbose_name='Wine sign')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AreaModel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.CountryModel')),
                ('quality_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.MarkModel')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.RegionModel')),
            ],
            options={
                'verbose_name_plural': 'Signs',
            },
            bases=('mainapp.metamodel',),
        ),
        migrations.AddField(
            model_name='areamodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.RegionModel'),
        ),
    ]
