# Generated by Django 3.0.5 on 2020-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.TextField(max_length=128, verbose_name='Region name'),
        ),
    ]
