# Generated by Django 3.0.5 on 2020-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200415_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.FileField(max_length=128, upload_to='', verbose_name='Region name'),
        ),
    ]
