# Generated by Django 3.0.5 on 2020-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200415_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='rating',
            field=models.PositiveIntegerField(default=1, verbose_name='Рейтинг'),
        ),
    ]
