# Generated by Django 3.0.5 on 2020-04-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_region_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='rating',
        ),
    ]
