# Generated by Django 3.0.5 on 2020-04-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_region_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='sign',
        ),
        migrations.AlterField(
            model_name='sign',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Area'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Country'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='quality_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.QualityMark'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Region'),
        ),
    ]
