# Generated by Django 3.0.5 on 2020-04-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200416_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitymark',
            name='area',
        ),
        migrations.RemoveField(
            model_name='qualitymark',
            name='country',
        ),
        migrations.RemoveField(
            model_name='qualitymark',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='quality_mark',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='QualityMark',
        ),
    ]
